---
- name: install mysql
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ mysql_pkg }}"
  register: mysql_installed

- name: enable mysql service
  become: yes
  service:
    name: "{{ mysql_service }}"
    enabled: yes

- name: start mysql service
  become: yes
  service:
    name: "{{ mysql_service }}"
    state: started
